update gh actions

diff --git a/.github/workflows/publish-docker-image-release.yml b/.github/workflows/publish-docker-image-release.yml
--- a/.github/workflows/publish-docker-image-release.yml
+++ b/.github/workflows/publish-docker-image-release.yml
@@ -64,46 +64,46 @@ jobs:
             CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
             BLOCKSCOUT_VERSION=v{{ env.RELEASE_VERSION }}-beta
 
-  merge-master-after-release:
-    name: Merge 'master' to specific branch after release
-    runs-on: ubuntu-latest
-    env:
-      BRANCHES: |
-        production-core-stg
-        production-eth-stg
-        production-harmony-mainnet-shard-0-stg
-        production-lukso-stg
-        production-optimism-goerli-stg
-        production-optimism-bedrock-goerli-stg
-        production-optimism-mainnet-stg
-        production-optimism-stg
-        production-rsk-stg
-        production-sokol-stg
-        production-xdai-stg
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set Git config
-      run: |
-          git config --local user.email "actions@github.com"
-          git config --local user.name "Github Actions"
-    - name: Merge master back after release
-      run: |
-          git fetch --unshallow
-          touch errors.txt
-          for branch in $BRANCHES;
-          do
-            git reset --merge
-            git checkout master
-            git fetch origin
-            echo $branch
-            git ls-remote --exit-code --heads origin $branch || { echo $branch >> errors.txt; continue; }
-            echo "Merge 'master' to $branch"
-            git checkout $branch
-            git pull || { echo $branch >> errors.txt; continue; }
-            git merge --no-ff master -m "Auto-merge master back to $branch" || { echo $branch >> errors.txt; continue; }
-            git push || { echo $branch >> errors.txt; continue; }
-            git checkout master;
-          done
-          [ -s errors.txt ] && echo "There are problems with merging 'master' to branches:" || echo "Errors file is empty"
-          cat errors.txt
-          [ ! -s errors.txt ]
+  # merge-master-after-release:
+  #   name: Merge 'master' to specific branch after release
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     BRANCHES: |
+  #       production-core-stg
+  #       production-eth-stg
+  #       production-harmony-mainnet-shard-0-stg
+  #       production-lukso-stg
+  #       production-optimism-goerli-stg
+  #       production-optimism-bedrock-goerli-stg
+  #       production-optimism-mainnet-stg
+  #       production-optimism-stg
+  #       production-rsk-stg
+  #       production-sokol-stg
+  #       production-xdai-stg
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - name: Set Git config
+  #     run: |
+  #         git config --local user.email "actions@github.com"
+  #         git config --local user.name "Github Actions"
+  #   - name: Merge master back after release
+  #     run: |
+  #         git fetch --unshallow
+  #         touch errors.txt
+  #         for branch in $BRANCHES;
+  #         do
+  #           git reset --merge
+  #           git checkout master
+  #           git fetch origin
+  #           echo $branch
+  #           git ls-remote --exit-code --heads origin $branch || { echo $branch >> errors.txt; continue; }
+  #           echo "Merge 'master' to $branch"
+  #           git checkout $branch
+  #           git pull || { echo $branch >> errors.txt; continue; }
+  #           git merge --no-ff master -m "Auto-merge master back to $branch" || { echo $branch >> errors.txt; continue; }
+  #           git push || { echo $branch >> errors.txt; continue; }
+  #           git checkout master;
+  #         done
+  #         [ -s errors.txt ] && echo "There are problems with merging 'master' to branches:" || echo "Errors file is empty"
+  #         cat errors.txt
+  #         [ ! -s errors.txt ]
