Update publish-docker-image-release.yml

diff --git a/.github/workflows/publish-docker-image-release.yml b/.github/workflows/publish-docker-image-release.yml
--- a/.github/workflows/publish-docker-image-release.yml
+++ b/.github/workflows/publish-docker-image-release.yml
@@ -10,15 +10,15 @@ on:
     types: [published]
 
 env:
-  OTP_VERSION: '25.2.1'
-  ELIXIR_VERSION: '1.14.3'
+  OTP_VERSION: "25.2.1"
+  ELIXIR_VERSION: "1.14.3"
 
 jobs:
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
     env:
-      RELEASE_VERSION: 5.1.5
+      RELEASE_VERSION: 5.1.1
     steps:
       - name: Check out the repo
         uses: actions/checkout@v3
@@ -39,7 +39,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v4
         with:
-          images: blockscout/blockscout
+          images: synxless/blockscout
 
       - name: Build & Push Docker image
         uses: docker/build-push-action@v3
@@ -47,71 +47,63 @@ jobs:
           context: .
           file: ./docker/Dockerfile
           push: true
-          cache-from: type=registry,ref=blockscout/blockscout:buildcache
-          cache-to: type=registry,ref=blockscout/blockscout:buildcache,mode=max
-          tags: blockscout/blockscout:latest, blockscout/blockscout:${{ env.RELEASE_VERSION }}
+          cache-from: type=registry,ref=synxless/blockscout:buildcache
+          cache-to: type=registry,ref=synxless/blockscout:buildcache,mode=max
+          tags: synxless/blockscout:latest, synxless/blockscout:${{ env.RELEASE_VERSION }}
           platforms: |
             linux/arm64
             linux/amd64
           build-args: |
             CACHE_EXCHANGE_RATES_PERIOD=
-            API_V1_READ_METHODS_DISABLED=false
+            DISABLE_READ_API=false
             DISABLE_WEBAPP=false
-            API_V1_WRITE_METHODS_DISABLED=false
-            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
-            ADMIN_PANEL_ENABLED=false
-            DECODE_NOT_A_CONTRACT_CALLS=false
-            MIXPANEL_URL=
-            MIXPANEL_TOKEN=
-            AMPLITUDE_URL=
-            AMPLITUDE_API_KEY=
+            DISABLE_WRITE_API=false
+            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
+            WOBSERVER_ENABLED=false
+            ADMIN_PANEL_ENABLED=
             CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
-            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
-            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
+            BLOCKSCOUT_VERSION=v{{ env.RELEASE_VERSION }}-beta
 
-  merge-master-after-release:
-    name: Merge 'master' to specific branch after release
-    runs-on: ubuntu-latest
-    env:
-      BRANCHES: |
-        production-core-stg
-        production-sokol-stg
-        production-eth-stg-experimental
-        production-eth-goerli-stg
-        production-lukso-stg
-        production-optimism-goerli-stg
-        production-optimism-mainnet-stg
-        production-optimism-opcraft-stg
-        production-xdai-stg
-        production-gc-chiado-stg
-        production-polygon-supernets-stg
-        production-base-goerli-stg
-        production-rsk-stg
-        production-neon-stg
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set Git config
-      run: |
-          git config --local user.email "actions@github.com"
-          git config --local user.name "Github Actions"
-    - name: Merge master back after release
-      run: |
-          git fetch --unshallow
-          touch errors.txt
-          for branch in $BRANCHES;
-          do
-            git reset --merge
-            git checkout master
-            git fetch origin
-            echo $branch
-            git ls-remote --exit-code --heads origin $branch || { echo $branch >> errors.txt; continue; }
-            echo "Merge 'master' to $branch"
-            git checkout $branch
-            git pull || { echo $branch >> errors.txt; continue; }
-            git merge --no-ff master -m "Auto-merge master back to $branch" || { echo $branch >> errors.txt; continue; }
-            git push || { echo $branch >> errors.txt; continue; }
-            git checkout master;
-          done
-          [ -s errors.txt ] && echo "There are problems with merging 'master' to branches:" || echo "Errors file is empty"
-          cat errors.txt
-          [ ! -s errors.txt ]
+  # merge-master-after-release:
+  #   name: Merge 'master' to specific branch after release
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     BRANCHES: |
+  #       production-core-stg
+  #       production-eth-stg
+  #       production-harmony-mainnet-shard-0-stg
+  #       production-lukso-stg
+  #       production-optimism-goerli-stg
+  #       production-optimism-bedrock-goerli-stg
+  #       production-optimism-mainnet-stg
+  #       production-optimism-stg
+  #       production-rsk-stg
+  #       production-sokol-stg
+  #       production-xdai-stg
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - name: Set Git config
+  #     run: |
+  #         git config --local user.email "actions@github.com"
+  #         git config --local user.name "Github Actions"
+  #   - name: Merge master back after release
+  #     run: |
+  #         git fetch --unshallow
+  #         touch errors.txt
+  #         for branch in $BRANCHES;
+  #         do
+  #           git reset --merge
+  #           git checkout master
+  #           git fetch origin
+  #           echo $branch
+  #           git ls-remote --exit-code --heads origin $branch || { echo $branch >> errors.txt; continue; }
+  #           echo "Merge 'master' to $branch"
+  #           git checkout $branch
+  #           git pull || { echo $branch >> errors.txt; continue; }
+  #           git merge --no-ff master -m "Auto-merge master back to $branch" || { echo $branch >> errors.txt; continue; }
+  #           git push || { echo $branch >> errors.txt; continue; }
+  #           git checkout master;
+  #         done
+  #         [ -s errors.txt ] && echo "There are problems with merging 'master' to branches:" || echo "Errors file is empty"
+  #         cat errors.txt
+  #         [ ! -s errors.txt ]
